### PR TITLE
Add justmisam/leitner, justmisam/lmq, and justmisam/PyLMQ repositories

### PR DESCRIPTION
**Pull request by justmisam**

### CODE REVIEW

**Comment by mehdy** [comment]
@justmisam Thanks for the PR! Although I've already merged the PR, I should've paid more attention to your repos and asked you about the **Leitner** repo.

Do you intend to keep working on the project or has it been just a project to practice coding?
If you want to keep working on it, I'd appreciate it if you add a bit more documentation to the project (how to use it, how to setup dev environment for contributing, etc), in order to make it a bit easier for new people to start contributing to it?

**Comment by justmisam** [comment]
@mehdy First of all, thanks for accepting the merge request. Well, it's not just a practice project, and it has made based on an Android application developed more than five years ago by me, and I'd still like to work on it with some ideas. Although it's so easy to develop, and people can read the user instruction on its [Cafebazaar page](https://cafebazaar.ir/app/ir.misam.leitner), I'll definitely add some proper documents for it as soon as possible.

**Comment by mehdy** [comment]
@justmisam Got it. That'd be great! Thanks.

**Comment by loreanvictor** [comment]
@justmisam thanks for the PR and the interest! on that topic, I would like to also recommend adding some issues to all three repositories, as it will give new contributors a clearer idea on how do you envision each project to evolve and how they can be of help on that path.

**Pull request merged**
