### PR TITLE
Add evryn/laravel-toman repository

### PR DESCRIPTION
**Pull request by AmirrezaNasiri**

### CODE REVIEW

**Comment by loreanvictor** [comment]
@AmirrezaNasiri thanks a lot for the PR! since looks like a pretty well-established project, it might seem intimidating for new people to contribute to. could you add further [guidelines for new contributors](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors), to ease that transition? additionally, outlining issues that new contributors could work on would be really helpful too.

**Comment by AmirrezaNasiri** [comment]
@loreanvictor Yup! It's available in [CONTRIBUTING.md](https://github.com/evryn/laravel-toman/blob/master/.github/CONTRIBUTING.md) and I've made some changes to it. Would you check it out again?

**Comment by loreanvictor** [comment]
ah my mistake, I conventionally look for it in the root of the repo so I missed it 😅 since the same confusion might happen for others, would you mind mentioning (and linking) it (maybe alongside the COC?) in the README as well? (or does including it in `.github` makes it automatically visible somewhere that I'm unfamiliar with?)

**Comment by AmirrezaNasiri** [comment]
@loreanvictor Aaaa it's OK :)
Github does actually treat `.md` files in `.github` just like they are in the root. Here is how it uses them:
issues

Putting them in `.github` doesn't give anything special except keeping root clear.
I added the [How to contribube](https://github.com/evryn/laravel-toman#how-to-contribute) section in the readme and of course, it's available in the [docs](https://evryn.github.io/laravel-toman/) too :)

**Comment by loreanvictor** [comment]
@AmirrezaNasiri perfect!

**Pull request merged**
