### PR TITLE
add ajangi open source repos

### PR DESCRIPTION
**Pull request by ajangi**

### CODE REVIEW

**Comment by mehdy** [comment]
@ajangi Thanks a lot for your contribution. Could you please add some [contribution guidelines](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) to your repos and maybe opening some issues for them as well to give contributors some clues where/how to start.

**Comment by ajangi** [comment]
For "php-rest-response" and "laravel-crypt-model" CONTRIBUTING.md file and issues added. For "gogit" repo only two issues are available now.

**Comment by mehdy** [comment]
@ajangi Great! Thanks! the `php-rest-response` and `laravel-crypt-model` are good to go! Would you please add a similar `CONTRIBUTING.md` to `gogit` as well so that I can merge this PR?

**Comment by ajangi** [comment]
Yeah sure.

**Comment by ajangi** [comment]
> @ajangi Great! Thanks! the `php-rest-response` and `laravel-crypt-model` are good to go! Would you please add a similar `CONTRIBUTING.md` to `gogit` as well so that I can merge this PR?

Contributing guide md file added.

**Comment by mehdy** [comment]
Thanks! I'm gonna merge it but the title of the document is still `PHP Rest Response` though. :D

**Comment by ajangi** [comment]
> Thanks! I'm gonna merge it but the title of the document is still `PHP Rest Response` though. :D

I'll fix it right now. Don't let anybody know this fact. 😂😂

**Pull request merged**
