### PR TITLE
Added Some Repos

### PR DESCRIPTION
**Pull request by amireshoon**
- [Black](https://github.com/amireshoon/Black)
- [Gow](https://github.com/amireshoon/gow)
- [MinifyAction](https://github.com/amireshoon/minifyAction)
- [Friends](https://github.com/amireshoon/Friends)

### CODE REVIEW

**Comment by mehdy** [comment]
Thanks a lot for the repos.
I think the Black repo needs a little bit more issues, contribution guides for newcomers.
And the Friends repo seems a bit controversial to me. I don't think it's a good fit for this hackathon.
What do you think guys? (@loreanvictor @negarjf @sina-mirhejazi @ebraminio)

**Comment by negarjf** [comment]
About the Friends repo, I think it is a fun and easy repo to contribute. It's good for the ones who want to practice forking and making a PR. On the other hand, it is not going to be a programming contribution. (Not sure if it's something that matters to the purposes of the hackethon.)
I'm afraid that it turns into a place for contributors to cheat the rating system, and work their way to the top of the rankings.

What I can suggest is instead of adding it to the main repo list, we suggest this Repo as a good playground for beginners in the tutorial section.

**Comment by loreanvictor** [comment]
@amireshoon seems like some files are accidentally included in the PR (`docs/index.html`, `first/README.md`). Could you only include the changed YML files? Otherwise the PR will have conflicts with main and be pretty tough to merge.

**Comment by amireshoon** [comment]
@loreanvictor I think it's better to discuss what I add and then I open another PR that includes only selected repos.

**Pull request closed without merging**
