### PR TITLE
Introducing Zarb project

### PR DESCRIPTION
**Pull request by b00f**
Zarb is designed fzrom the ground up to be a “pure” blockchain protocol.
Read more about zarb [here](https://zarb.network/)

### CODE REVIEW

**Comment by mehdy** [comment]
@b00f Thanks for the PR! Could you please a `maintainers` field containing the list of its maintainer(s) usernames?
Check [this](https://github.com/OSS-Hackathon/IranOpenSourceHackathon/blob/main/first/repos/cafebazaar/keepalived-exporter.yaml) out as an example.

**Comment by b00f** [comment]
@mehdy 
I followed the README and as I noticed it is optional. But it's OK. I will update the PR.

**Comment by loreanvictor** [comment]
> I followed the README and as I noticed it is optional. But it's OK. I will update the PR.

perhaps the wording was a bit confusing, I changed it a bit for further clarity:

> 👉 If your repo belongs to a company or organization, you **MUST** specify maintainers independently.

**Comment by loreanvictor** [comment]
@b00f while this satisfies all requirements, due to the non-trivial and well-established project architecture, I would also highly recommend expanding the [contribution segment](https://github.com/zarbchain/zarb-go#contribution) on README (or adding a separate contribution guideline document) outlining project structure and guidelines for contribution, as it would perhaps make it easier for new comers to understand and contribute to the project.

**Comment by b00f** [comment]
@loreanvictor 

Thanks for allowing the Zarb project to be part of this amazing hackathon.

You are so welcome if you can help Zarb to have a nice Contribution guideline. hope to see you there...

**Comment by loreanvictor** [comment]
> You are so welcome if you can help Zarb to have a nice Contribution guideline. hope to see you there...

I mean I would need to be much more familiarized with the code base, structure, design principles, longterm goals, etc. to be able to confidently write a usable contribution guideline for such a project, but I'll look into it if I (ever) get the free time 😅

**Comment by b00f** [comment]
@loreanvictor This is really kind of you. We do believe that for a Blockchain everything should be decentralized even ideas and implementation.

**Pull request merged**
